apiVersion: v1
kind: Service
metadata:
  name: artemis-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    workload.user.cattle.io/workloadselector: statefulSet-artemis-artemis-mysql