apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: user-gpcv5
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-artemis-gateway
  name: gateway
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-artemis-gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-artemis-gateway
    spec:
      securityContext: # Pod-level security
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
        supplementalGroups: [2000]
      containers:
      - name: gateway
        image: ghcr.io/ls1intum/artemis-gateway:pr-4965
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: 8080tcp02
          protocol: TCP
        envFrom:
        - configMapRef:
            name: gateway
            optional: false
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: 
            drop: ["ALL"]
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30