apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artemis-secrets
  namespace: external-secrets
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" 
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "artemis" # Allow reflection to the "artemis" namespace
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: artemis-secrets
    creationPolicy: Owner
  data:
  - secretKey: artemis.athena.secret
    remoteRef:
      key: "ARTEMIS_ATHENA_SECRET"
  - secretKey: artemis.continuous-integration.password
    remoteRef:
      key: "ARTEMIS_CI_PASSWORD"
  - secretKey: artemis.continuous-integration.token
    remoteRef:
      key: "ARTEMIS_CI_TOKEN"
  - secretKey: artemis.lti.oauth-key
    remoteRef:
      key: "ARTEMIS_LTI_OAUTH_KEY"
  - secretKey: artemis.user-management.external.password
    remoteRef:
      key: "ARTEMIS_USER_EXTERNAL_PASSWORD"
  - secretKey: artemis.user-management.internal-admin.password
    remoteRef:
      key: "ARTEMIS_ADMIN_PASSWORD"
  - secretKey: artemis.user-management.ldap.password
    remoteRef:
      key: "ARTEMIS_LDAP_PASSWORD"
  - secretKey: artemis.version-control.password
    remoteRef:
      key: "ARTEMIS_VCS_PASSWORD"
  - secretKey: artemis.version-control.token
    remoteRef:
      key: "ARTEMIS_VCS_TOKEN"